'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';
import toast from 'react-hot-toast';
import { createCollection } from '@/lib/supabase/gallery';
import { THEME_COLORS, EMOJI_OPTIONS } from '@/constants/gallery';

interface CreateCollectionModalProps {
  onClose: () => void;
  onCreate: () => void;
}

export default function CreateCollectionModal({ onClose, onCreate }: CreateCollectionModalProps) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [emoji, setEmoji] = useState('🎨');
  const [themeColor, setThemeColor] = useState(THEME_COLORS[0].color);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!name.trim()) {
      toast.error('컬렉션 이름을 입력해주세요');
      return;
    }

    setLoading(true);
    try {
      await createCollection({
        name: name.trim(),
        description: description.trim() || undefined,
        emoji,
        themeColor,
        organizationType: 'manual',
        coverType: 'auto',
        itemCount: 0,
        isPublic: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: '', // Will be set by Supabase
        id: '' // Will be generated by Supabase
      });

      toast.success('✨ 컬렉션이 생성되었습니다!');
      onCreate();
    } catch (error) {
      console.error('Failed to create collection:', error);
      toast.error('컬렉션 생성에 실패했습니다');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-black/50"
        />

        {/* Modal */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="relative bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 z-10"
        >
          {/* Close Button */}
          <button
            onClick={onClose}
            className="absolute top-4 right-4 p-2 rounded-full hover:bg-neutral-100 transition-colors"
          >
            <X className="w-5 h-5 text-neutral-600" />
          </button>

          {/* Title */}
          <div className="mb-8">
            <p className="text-xs uppercase tracking-widest text-neutral-400 mb-2">New Collection</p>
            <h2 className="text-3xl font-light text-black tracking-tight">Create Collection</h2>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Name */}
            <div>
              <label className="block text-xs uppercase tracking-wider text-neutral-500 mb-3">
                Name *
              </label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g., Comfort in Art"
                className="w-full px-0 py-3 border-0 border-b border-neutral-300 focus:border-black focus:ring-0 text-lg font-light tracking-tight placeholder:text-neutral-300"
                maxLength={50}
              />
            </div>

            {/* Description */}
            <div>
              <label className="block text-xs uppercase tracking-wider text-neutral-500 mb-3">
                Description (Optional)
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="A brief note about this collection..."
                rows={3}
                className="w-full px-0 py-2 border-0 border-b border-neutral-300 focus:border-black focus:ring-0 resize-none placeholder:text-neutral-300"
                maxLength={200}
              />
            </div>

            {/* Emoji */}
            <div>
              <label className="block text-xs uppercase tracking-wider text-neutral-500 mb-3">
                Icon
              </label>
              <div className="flex gap-2 flex-wrap">
                {EMOJI_OPTIONS.map((em) => (
                  <button
                    key={em}
                    type="button"
                    onClick={() => setEmoji(em)}
                    className={`
                      p-2 text-xl border transition-all
                      ${emoji === em ? 'border-black bg-neutral-50' : 'border-neutral-200 hover:border-neutral-400'}
                    `}
                  >
                    {em}
                  </button>
                ))}
              </div>
            </div>

            {/* Theme Color */}
            <div>
              <label className="block text-xs uppercase tracking-wider text-neutral-500 mb-3">
                Theme Color
              </label>
              <div className="flex gap-2 flex-wrap">
                {THEME_COLORS.map((theme) => (
                  <button
                    key={theme.id}
                    type="button"
                    onClick={() => setThemeColor(theme.color)}
                    className={`
                      relative w-12 h-12 border-2 transition-all
                      ${themeColor === theme.color ? 'border-black scale-110' : 'border-neutral-200'}
                    `}
                    style={{ backgroundColor: theme.color }}
                    title={theme.name}
                  />
                ))}
              </div>
            </div>

            {/* Submit */}
            <div className="flex gap-3 pt-6 border-t border-neutral-100">
              <button
                type="button"
                onClick={onClose}
                className="flex-1 px-6 py-3 border border-neutral-300 text-sm uppercase tracking-wider text-neutral-600 hover:bg-neutral-50 transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading || !name.trim()}
                className="flex-1 px-6 py-3 bg-black text-white text-sm uppercase tracking-wider hover:bg-neutral-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? 'Creating...' : 'Create'}
              </button>
            </div>
          </form>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
