[phases.build]
dependsOn = ["install"]
cmds = ["npm run build:railway"]

[phases.install]
cmds = ["npm ci --only=production", "npm ci"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
SKIP_ENV_VALIDATION = "true"